### ISSUE TITLE
Decide on a license

### ISSUE THREAD

**Issue by wbadart** [wbadart/coolsnappy#1] opened 2020-04-09 15:20 UTC
When standing up the repo, I reflexively plopped in the MIT license. Let's think ahead a little bit and be sure that this is the most appropriate way to go. For example, are we interested in a [copy-left][01] license? Or for another example, if we go the Haskell route, would we want the BSD-3 for uniformity with the rest of the ecosystem?

**Acceptance Criteria:**

- [x] A LICENSE file (can be the current MIT file)
- [x] Justification for the choice of license
- [x] Comparison to other licenses considered

The latter two can just be comments on this issue.

## Resources:

- https://arstechnica.com/gadgets/2020/02/how-to-choose-an-open-source-license/
- https://opensource.org/licenses
- https://en.wikipedia.org/wiki/Open-source_license
  - https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses
- https://choosealicense.com/licenses

[01]: https://opensource.org/faq#copyleft

**Comment by wbadart** [comment] 2020-04-13 21:55
One more resource: https://opensource.guide/starting-a-project/#choosing-a-license

**Comment by alexandratsitsiringos** [comment] 2020-04-21 03:11
As I explored this issue, it seems that it all comes down to one idea: whether or not we want to maintain the idea of "software freedom" strongly. 

-  If we want to allow anyone to do anything at any time with the software, we should use the MIT or new (3-clause) BSD license, i.e. no copyleft and no discussion of patents

- If we want to allow anyone to do anything with the software, but feel something needs to be said about patents and license termination in the face of litigation, or we want a license that corporate counsel would be more comfortable reading then we should look at either the Apache 2.0 license or possibly the Microsoft Permissive License. 

- If we want others to be able to build around our software, but want to ensure changes to the core software project itself remain open source, we should use Eclipse Public License, the newer Mozilla Public License 2.0, or the Microsoft Reciprocal License. 

- If we want to support software freedom or want to ensure that if our software source is used anywhere that the resulting derivatives are maximally published as open source ensuring software freedom, then we should look to GPL2.0 or GPL3.0. 

One of the most useful [classifications ](https://www.semanticscholar.org/paper/Open-Source-Licenses-and-the-Creative-Commons-and-Lin-Ko/0625aada49caa66436ee6e3fac88542678100d0e) of open source licenses i found 

![image](https://user-images.githubusercontent.com/54826163/79821212-2ccbb900-835c-11ea-8d87-0851035db7e5.png)

**Comment by alexandratsitsiringos** [comment] 2020-04-29 15:16
Based on the question "What if we wanted to turn the open source project into a startup, I've done a lot more research to supplement the original. Let's start from the basics, assuming that when mentioning a startup we mean that we want to gain proprietary rights over the software. 

Proprietary software is software that is owned by an individual or a company (usually the one that developed it. There are almost always major restrictions on its use, and its source code is almost always kept secret. This is different from commercial software. Commercial software is produced for sale or serves commercial purposes. Commercial software can be proprietary software or free and open-source software.

The balance lies in what is less risky for us, and what is risky for the people that might want to use our code. From an outsider perspective, here is how licenses can be separated: 

- Low risk. Permissive licenses are consider low risk because it’s easy to meet their reuse requirements: Usually you just have to retain the copyright notice, but you don’t have to expose your source code. Examples are the Apache and MIT Licenses.

- Medium risk. Semi-permissive licenses, sometimes referred to as limited licenses, weak copyleft licenses, or simple copyleft licenses, are considered medium risk because if you modify the code, you have to release the modifications, but not your whole application, under the same license. Different licenses define “modification” differently. Examples are the Mozilla and the Eclipse Public Licenses.

- High risk. Restrictive licenses carry a great deal of legal risk. If you use a component with one of these licenses, you might be legally obligated to release your entire application code. Examples are the GNU GPL and GNU LGPL.


Essentially, if someone else used our GPL licensed software in a business, it would be required that they are constantly vigilant to make sure that our code does not appear in their proprietary licensed software. BSD, Apache, MIT and other "attribution" style licenses only require them to provide attribution to us, as developers of the source code they are using in their product. An important note is that this is not regarding use but distribution - a user or company can use our own GPL v3 code coupled with proprietary code and keep all that closed AS LONG AS THEY DO NOT DISTRIBUTE IT. 

From out perspective, not that of the outsider using our code: 
**GPL:** 
If the goal is to help establish the one de facto software platform and we want to be seen as the go-to for support and application of that software in the business world, then choosing a GPL license (and contributing to the development of that software) would be the best choice. 

**BSD/Apache/MIT:** 
If the goal is to develop and sell software that might require broad adoption of some API or integration standard, then choosing to invest in a open source software license that makes it easy for other companies to adopt those standards in their own products may help us realize that goal.

So now we finally want to take the step and convert to a proprietary license for out startup. 

There are two cases in which it is possible to effectively change the copyright license on existing code.
1. The existing copyright license gives you the right to change the license or to sub-license the code. The GPL licenses do not fall in this category of licenses. 
2. You are one of the copyright holders on the code and all copyright holders explicitly agree to the license change. If you ever accepted contributions from others without an explicit re-assignment of the copyright, then you the copyright on those contributions belongs to the person that wrote the contribution and you are bound by the license terms that were in effect when the contribution was made. If you want to change the license, you must get permission from all contributers. If any one of them refuses permission, then you must either remove their contributions entirely or forget about the license change.  In anticipation of possible relicensing, some projects require a contributor license agreement (CLA) or copyright assignment so that the maintainer (here, the company) is not limited by the outbound license. However, many contributors may refuse to sign CLAs precisely because of this issue. A recent example of a CLA-assisted relicensing was MongoDB's change from AGPL to the (non-Open Source) SSP

But this is about EXISTING code. Nothing prevents us from using multiple licenses on our project for future code. Say we complete project A, and we used a GPL v3 license for that.  As copyright owners, we can use that code on project B, and combine it with closed-source/proprietary code and sell the whole project B as proprietary (while keeping project A open source). A caveat, of course, is that we would not be allowed to use OTHER GPL libraries in our proprietary distributed software (as we have no right to use them under a different license).


Some examples of how this has been used in the past:
1. The MySQL and MariaDB story: MySQL was GPL or proprietary, and was taken only proprietary. MariaDB started with the last GPL version and continues to be open source. 
2. Relicensing example: A recent example of a CLA-assisted relicensing was MongoDB's change from AGPL to the (non-Open Source) SSPL.
3. This is also a revenue stream idea: A popular option lately is to release a GPL version, and sell more permissive licenses to people who want to use the software in a closed-source program. For instance, that is how Red Hat and Ada Core make money off of their GPL compilers.

For these reasons, I think we should choose GPL, and specifically GPL v3. It would require others to release their source code or clearly separate what they use from our code from their proprietary code in their distributed software - thus allowing us to retain the most “control” over what we produce. If we were to use MIT or another license that is more permissive, they would provide attribution to us but could otherwise build a whole product of their own using our code and keep the source code closed. 

https://opensource.stackexchange.com/questions/9576/can-i-use-my-own-gpled-code-in-my-closed-source-program
https://www.quora.com/What-are-the-most-restrictive-business-unfriendly-open-source-licenses
https://softwareengineering.stackexchange.com/questions/47032/can-i-use-gpl-software-in-a-commercial-application
https://www.quora.com/Can-I-use-the-GPLv3-license-for-my-commercial-application
https://www.quora.com/Can-I-relicense-my-GPL-project
https://www.synopsys.com/blogs/software-security/open-source-licenses/

Important Note: 
How do github projects work if they are not open source? You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

**Closed** 2020-06-25 23:09 UTC
Labels: size:3, task
